<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>NotificationService</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\common\Common.API\Common.API.csproj" />
      <ProjectReference Include="..\..\common\MessageQueue\MessageQueue.csproj" />
      <ProjectReference Include="..\NotificationService.BLL\NotificationService.BLL.csproj" />
      <ProjectReference Include="..\NotificationService.DAL\NotificationService.DAL.csproj" />
      <ProjectReference Include="..\..\common\Common.Auth\Common.Auth.csproj" />
    </ItemGroup>
    
</Project>
