<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>CrawlerService.Hangfire</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Hangfire.AspNetCore" Version="1.8.17" />
      <PackageReference Include="Hangfire.Mongo" Version="1.10.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CrawlerService.BLL.Abstractions\CrawlerService.BLL.Abstractions.csproj" />
    </ItemGroup>

</Project>
