<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Common.API</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Extensions\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common\Common.csproj" />
      <ProjectReference Include="..\Logger\Logger.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.3" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.3" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="8.1.0" />
    </ItemGroup>

</Project>
